### PR TITLE
Allow to build jobs with/without parameters

### PR DESCRIPTION
**Pull request by NikonNLG**
This fix allow to build jobs without parameters, or add other, except hardcoded "branch"

### CODE REVIEW

**Comment by NikonNLG** [comment]
@emedvedev Do you want that I make some changes for this PR?

**Comment by Kami** [comment]
The change looks good to me - thanks!

Please just update changelog file and bump patch version in pack.yaml.

Thanks

**Comment by NikonNLG** [comment]
@Kami thanks. Updated now.

**Comment by Kami** [comment]
Merged, thanks.

**Pull request merged**
