### PR TITLE
v0.7.0 - pack enhancements

### PR DESCRIPTION
**Pull request by emptywee**
* Add `get_runnings_builds` action to get all currently running builds.
 * Rename `list_running_jobs` -> `list_jobs` to reflect its meaning properly, the old name was misleading.
 * Updated `build_job_enh` to support `max_wait` parameter (wait for about this many seconds to get the job executed).
 * Updated docs

### CODE REVIEW

**Comment by emptywee** [comment]
@LindsayHill hey, happy new year! Could you see if this can be merged when you get a chance?

**Comment by LindsayHill** [comment]
Sorry for the delay, just getting back into the swing of things.

Looks like there's a bit of inconsistency with `get_runnings_builds` vs `get_running_builds` - the file and action names switch between them. It should be `get_running_builds`.

**Comment by emptywee** [comment]
Hmm, let me check...

**Comment by emptywee** [comment]
I guess it was just a typo in the docs :)

**Comment by LindsayHill** [comment]
Also a filename change. Have fixed that here. Once checks complete, I'll merge.

**Comment by emptywee** [comment]
Oh, thanks! Did not notice it at all :(

**Pull request merged**
